# Generated by Django 5.2.1 on 2025-05-20 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_roomimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='price_per_night',
        ),
    ]
