# Generated by Django 5.2.1 on 2025-06-06 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_hotelimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='image',
        ),
    ]
