# Generated by Django 5.2.1 on 2025-06-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_room_bathroom_room_bedroom_room_electronics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='rating',
            field=models.PositiveIntegerField(default=4),
            preserve_default=False,
        ),
    ]
