# Generated by Django 5.2.1 on 2025-06-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_emailconfirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='code',
            field=models.CharField(max_length=6),
        ),
    ]
