# Generated by Django 5.2.1 on 2025-06-09 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_emailconfirmation_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailConfirmation',
        ),
    ]
